---
public_ssh_key_path: <path_to_your_public_ssh_key_file>
service_account_username: <your_service_account_email>
service_account_credentials_json_file_path: <path_to_your_json_file>
project_id: <your_project_id>

# the cloud provider image is an OS image name that used to deploy OS on the provisioned nodes on GCP.
# the list of support images can be found at https://cloud.google.com/compute/docs/images#os-compute-support
cloud_provider_image: <name_of_an image_supported_by_GCP>
instance_type: f1-micro

custom_image: null

# the name of the datacenter, the number of nodes, the instance type and the image 
# to deploy on each cluster that you want to make a provisioing.
# If you do not specify the instance_type and the image for each cluster, 
# it will be the above value of cloud_provider_image and instance_type and the same for all clusters.

clusters:
    - cluster: us-central1-a
      n_nodes: 1
      instance_type: e2-standard-2
      image: null

    - cluster: europe-west3-a
      n_nodes: 2
      instance_type: f1-micro
      image: null