---
# the total time to keep the reserved nodes running
walltime: 3:00:00

# the OS image name (or environment name) that used to deploy OS on the reserved nodes on G5k system.
# the list of possible OS images can be found at /https://www.grid5000.fr/w/Advanced_Kadeploy#Search_and_deploy_an_existing_environment
cloud_provider_image: debian10-x64-big

# the path to your custom image that used to deploy OS on the reserved nodes on G5k system.
# follow this link to make your custom image: https://www.grid5000.fr/w/Advanced_Kadeploy#How_can_I_make_my_own_environment.3F
custom_image: null

# the name of the cluster and the number of nodes on each cluster that you want to make a reservation
clusters:
    - cluster: econome
      n_nodes: 10

    - cluster: dahu
      n_nodes: 3

    - cluster: graphite
      n_nodes: 7